// Static data used as filters in search page
const mealTypes = [
    "Afternoon tea",
    "Breads",
    "Breakfast",
    "Brunch",
    "Buffet",
    "Canapes",
    "Cheese Course",
    "Cocktails",
    "Condiment",
    "Dessert",
    "Dinner",
    "Drink",
    "Fish Course",
    "Lunch",
    "Main course",
    "Pasta",
    "Side dish",
    "Snack",
    "Soup",
    "Starter",
    "Supper",
    "Treat",
    "Vegetable",
  ],
  mealImages = [
    "https://cdn2.rsc.org.uk/sitefinity/images/catering/social-images/afternoon-tea-rooftop-restaurant-2022_2021_elin-englund_323478.tmb-gal-1340.jpg?sfvrsn=cfacb521_1",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Anadama_bread_%281%29.jpg/1200px-Anadama_bread_%281%29.jpg",
    "https://thebigmansworld.com/wp-content/uploads/2022/01/healthy-breakfast-recipes.jpeg",
    "https://assets.vogue.in/photos/6177f1ca9e58448a52772117/4:3/w_1704,h_1278,c_limit/Mike_Tsang-249-1_LR_GROUP.jpg",
    "https://images.thrillophilia.com/image/upload/s--Gz8lZEqe--/c_fill,g_auto,h_600,q_auto,w_975/f_auto,fl_strip_profile/v1/images/photos/000/239/379/original/1587729886_b1.jpg.jpg?1587729886",
    "https://preppykitchen.com/wp-content/uploads/2018/08/canape-recipe2.jpg",
    "https://foodscience.psu.edu/workshops/the-science-and-art-of-cheese-making-short-course/@@images/image",
    "https://c.ndtvimg.com/2022-05/b61ivn8_cocktails_625x300_12_May_22.jpg?im=FaceCrop,algorithm=dnn,width=620,height=350",
    "https://www.foodbusinessnews.net/ext/resources/2020/9/healthy-condiments_lead.jpg?t=1600101556&width=1080",
    "https://img.taste.com.au/xi2t8DpL/taste/2016/11/lemon-panna-cotta-with-vodka-blueberry-syrup-92005-1.jpeg",
    "https://www.eatthis.com/wp-content/uploads/sites/4/2021/01/chicken-and-broccoli.jpg?quality=82&strip=1",
    "https://www.acouplecooks.com/wp-content/uploads/2021/06/Strawberry-Water-006.jpg",
    "https://www.yummyntasty.com/wp-content/uploads/2012/10/karimeen_fry.jpg",
    "https://www.yummytummyaarthi.com/wp-content/uploads/2020/09/1-2.jpg",
    "https://vismaifood.com/storage/app/uploads/public/e12/7b7/127/thumb__700_0_0_0_auto.jpg",
    "https://frommybowl.com/wp-content/uploads/2020/01/One_Pot_Pasta_Vegetables_Vegan_FromMyBowl-6.jpg",
    "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/delish-191907-cauliflower-tots-0197-portrait-pf-1565967612.jpg",
    "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/20191219-seo-keto-tortilla-chips-delish-ehg-8872-1578952035.jpg",
    "https://www.simplyrecipes.com/thmb/94_qZrx8zWiWc7eSAyvJ7xDsE-I=/2000x1333/filters:fill(auto,1)/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2019__04__Easy-Carrot-Soup-Hero-2-cc00a570b56a492cba2142d3a797f7c5.jpg",
    "https://c.ndtvimg.com/2019-04/gbkiutf8_chicken-tikka-650_650x400_09_April_19.jpg?im=FaceCrop,algorithm=dnn,width=1200,height=675",
    "https://static.independent.co.uk/2021/12/06/12/iStock-1222741038.jpg?quality=75&width=982&height=726&auto=webp",
    "https://images.pexels.com/photos/1059905/pexels-photo-1059905.jpeg?cs=srgb&dl=pexels-chan-walrus-1059905.jpg&fm=jpg",
    "https://realfood.tesco.com/media/images/Veggie-rice-bowl-1400x919-mini-ba621247-21ff-419b-9604-3a27a255b90b-0-1400x919.jpg",
  ],
  dietTypes = [
    "Dairy-free",
    "Egg-free",
    "Gluten-free",
    "Healthy",
    "High protein",
    "High-fibre",
    "Keto",
    "Low calorie",
    "Low carb",
    "Low fat",
    "Low sugar",
    "Nut-free",
    "Vegan",
    "Vegetarian",
  ],
  timeFilters = [
    { lte10: "10 minutes or less" },
    { lte30: "30 minutes or less" },
    { lte60: "1 hour or less" },
    { gt60: "Over 1 hour" },
  ],
  cuisineTypes = [
    "Afghan",
    "African",
    "American",
    "Asian",
    "Australian",
    "Austrian",
    "Azerbaijan",
    "Balinese",
    "Brazilian",
    "British",
    "Caribbean",
    "Chinese",
    "Cuban",
    "Danish",
    "Dinner",
    "Eastern European",
    "Egyptian",
    "English",
    "Finland",
    "French",
    "German",
    "Greek",
    "Hungarian",
    "Indian",
    "Indonesian",
    "Irish",
    "Italian",
    "Jamaican",
    "Japanese",
    "Jewish",
    "Korean",
    "Latin American",
    "Lithuanian",
    "Mediterranean",
    "Mexican",
    "Middle Eastern",
    "Moroccan",
    "Nepalese",
    "North African",
    "Persian",
    "Peruvian",
    "Polish",
    "Portuguese",
    "Scandinavian",
    "Scottish",
    "Spanish",
    "Swedish",
    "Swiss",
    "Taiwanese",
    "Thai",
    "Tunisian",
    "Turkish",
    "Vietnamese",
    "Welsh",
  ],
  calorieRange = [
    { lte250: "250kcal and under" },
    { lte500: "upto 500kcal" },
    { lte750: "upto 750kcal" },
    { lte1000: "upto 1000kcal" },
    { lte1500: "upto 1500kcal" },
    { gt1500: "Over 1500kcal" },
  ],
  difficultyRanges = ["Easy", "More effort", "A challenge"],
  ratingRanges = [
    { gte1: "1 Star+" },
    { gte2: "2 Star+" },
    { gte3: "3 Star+" },
    { gte4: "4 Star+" },
    { eq5: "5 Stars" },
  ],
  servingRanges = [1, 2, 3, 4, 5, 6, 7, 8, "9+"],
  filters = [
    {
      name: "Meal type",
      "full-width": true,
      slug: "mealTypes",
      data: mealTypes,
    },
    {
      name: "Total Time",
      "full-width": false,
      slug: "timeFilters",
      data: timeFilters,
    },
    {
      name: "Diet type",
      "full-width": true,
      slug: "dietTypes",
      data: dietTypes,
    },
    {
      name: "Calories",
      "full-width": false,
      slug: "calorieRange",
      data: calorieRange,
    },
    {
      name: "Difficulty",
      "full-width": false,
      slug: "difficultyRanges",
      data: difficultyRanges,
    },
    {
      name: "Cuisine",
      "full-width": true,
      slug: "cuisineTypes",
      data: cuisineTypes,
    },
    {
      name: "Rating",
      "full-width": false,
      slug: "ratingRanges",
      data: ratingRanges,
    },
    {
      name: "Servings",
      "full-width": false,
      slug: "servingRanges",
      data: servingRanges,
    },
  ];
export {
  filters,
  dietTypes,
  mealTypes,
  mealImages,
  timeFilters,
  cuisineTypes,
  calorieRange,
  difficultyRanges,
  ratingRanges,
  servingRanges,
};
