// Static data used as filters in search page
const filters = [
    { name: "Meal type", "full-width": true },
    { name: "Total Time", "full-width": false },
    { name: "Diet type", "full-width": true },
    { name: "Calories", "full-width": false },
    { name: "Difficulty", "full-width": false },
    { name: "Cuisine", "full-width": true },
    { name: "Rating", "full-width": false },
    { name: "Servings", "full-width": false },
  ],
  mealTypes = [
    "Afternoon tea",
    "Breads",
    "Breakfast",
    "Brunch",
    "Buffet",
    "Canapes",
    "Cheese Course",
    "Cocktails",
    "Condiment",
    "Dessert",
    "Dinner",
    "Drink",
    "Fish Course",
    "Lunch",
    "Main course",
    "Pasta",
    "Side dish",
    "Snack",
    "Soup",
    "Starter",
    "Supper",
    "Treat",
    "Vegetable",
  ],
  dietTypes = [
    "Dairy-free",
    "Egg-free",
    "Gluten-free",
    "Healthy",
    "High protein",
    "High-fibre",
    "Keto",
    "Low calorie",
    "Low carb",
    "Low fat",
    "Low sugar",
    "Nut-free",
    "Vegan",
    "Vegetarian",
  ],
  timeFilters = {
    lte10: "10 minutes or less",
    lte30: "30 minutes or less",
    lte60: "1 hour or less",
    gt60: "Over 1 hour",
  },
  cuisineTypes = [
    "Afghan",
    "African",
    "American",
    "Asian",
    "Australian",
    "Austrian",
    "Azerbaijan",
    "Balinese",
    "Brazilian",
    "British",
    "Caribbean",
    "Chinese",
    "Cuban",
    "Danish",
    "Dinner",
    "Eastern European",
    "Egyptian",
    "English",
    "Finland",
    "French",
    "German",
    "Greek",
    "Hungarian",
    "Indian",
    "Indonesian",
    "Irish",
    "Italian",
    "Jamaican",
    "Japanese",
    "Jewish",
    "Korean",
    "Latin American",
    "Lithuanian",
    "Mediterranean",
    "Mexican",
    "Middle Eastern",
    "Moroccan",
    "Nepalese",
    "North African",
    "Persian",
    "Peruvian",
    "Polish",
    "Portuguese",
    "Scandinavian",
    "Scottish",
    "Spanish",
    "Swedish",
    "Swiss",
    "Taiwanese",
    "Thai",
    "Tunisian",
    "Turkish",
    "Vietnamese",
    "Welsh",
  ],
  calorieRange = {
    lte250: "250kcal and under",
    lte500: "upto 500kcal",
    lte750: "upto 750kcal",
    lte1000: "upto 1000kcal",
    lte1500: "upto 1500kcal",
    gt1500: "Over 1500kcal",
  },
  difficultyRanges = ["Easy", "More effort", "A challenge"],
  ratingRanges = {
    gte1: "1 Star+",
    gte2: "2 Star+",
    gte3: "3 Star+",
    gte4: "4 Star+",
    eq5: "5 Stars",
  },
  servingRanges = [1, 2, 3, 4, 5, 6, 7, 8, "9+"];
export {
  filters,
  dietTypes,
  mealTypes,
  timeFilters,
  cuisineTypes,
  calorieRange,
  difficultyRanges,
  ratingRanges,
  servingRanges,
};
